// SPDX-License-Identifier: MIT
pragma solidity ^0.8.2;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "./IAaveIncentivesController.sol";

interface IAToken is IERC20 {

  function UNDERLYING_ASSET_ADDRESS() external view returns (address);
  function getIncentivesController() external view returns (IAaveIncentivesController);

  // always returns the most up to date balance of the user, including their 
  // principal balance + the interest generated by the principal balance.
  function balanceOf(address user)
    external
    view
    override(IERC20)
    returns (uint256);
}
