export const DOCS_PATH = 'docs/';
export const CONTRACTS_PATH_IN_DOCS = 'contracts/';
export const CONTRACT_DOCS_PATH = `${DOCS_PATH}${CONTRACTS_PATH_IN_DOCS}`;
export const SUMMARY_PATH = `${DOCS_PATH}SUMMARY.md`
export const README_NAME = 'README.md';

export const TOC_START_MARK = '<!-- CONTRACTS_AUTOGENERATED_TOC_START -->';
export const TOC_END_MARK = '<!-- CONTRACTS_AUTOGENERATED_TOC_END -->';